### ISSUE TITLE
Adding a contribution guideline

### ISSUE THREAD

**Issue by Prakash-Haldar** [geekymeeky/chitchat#6]
Assign this issue to me  as DCP21

**Comment by geekymeeky** [comment]
Hi @Prakash-Haldar 

Thanks for taking it up! Please feel free to take some material from [here](https://github.com/geekymeeky/JS-games/blob/main/CONTRIBUTING.md).

Overall focus on creating a Contributor's Guide that would encompass the following:

- How to create an Issue?
- How to create a Pull Request?
- Getting PRs reviewed

**Comment by Prakash-Haldar** [comment]
I have created a pull request . Please see to it

**Comment by Prakash-Haldar** [comment]
@geekymeeky

**Comment by Prakash-Haldar** [comment]
I do all the necessary changes which you mentioned . Pls check it @geekymeeky

**Comment by Prakash-Haldar** [comment]
After That I will work on the issue #13 . 
Thanks for assigning issue to me. Its a Great opportunity to work With you @geekymeeky

**Comment by geekymeeky** [comment]
Closed via #12

**Comment by Prakash-Haldar** [comment]
Plz send the google form link of DevIncept
